export const CREATE_REMINDER = 'CREATE_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';
export const UPDATE_REMINDER = 'UPDATE_REMINDER';
export const REORDER_REMINDERS = 'REORDER_REMINDERS';

export const SET_CALENDAR_MONTH = 'SET_CALENDAR_MONTH';

export const SHOW_FORM_DIALOG = 'SHOW_FORM_DIALOG';
export const HIDE_FORM_DIALOG = 'HIDE_FORM_DIALOG';
